### ISSUE TITLE
Messages not send

### ISSUE THREAD

**Issue by georgemakrakis** [Holochain/holochat#32]
Hello,
i am new to the Holochain development procedure and i successfully run the HoloWolrd demo on my Ubuntu 16.04 machine. But when i came in holochat i followed the same way to run it using the **hcdev --no-nat-upnp --mdns web** command. I opend the browser on localhost:4141, registered and made a room successfully, but after that i could send any message to my room. The following screenshots are from the terminal:
![image](https://user-images.githubusercontent.com/13571540/38872944-38c45a24-425d-11e8-80ef-20c1a65d896d.png)
![image](https://user-images.githubusercontent.com/13571540/38873014-67a168dc-425d-11e8-9f41-602d642a01c6.png)

Any help will be appreciated thanks!

**Comment by zo-el** [comment]
Hi @georgemakrakis ,
Sorry for the late reply.
We are working on creating a UI in react now, but I just create a branch called develop-ui, that Should work for now whit the messages. 
We are working on adding more features and most of them will be in the React version.
